name: Publish Docker image

on:
  pull_request:
    branches: ["main"]

jobs:
  docker_build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/main.dockerfile
