name: Rust Check & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start the postgres service that is already in the runner ubuntu image
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password'"
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: Install sqlx cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli --no-default-features --features rustls,postgres
      - name: Prepare db for testing
        run: source .env && sqlx database reset -y
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-rust-${{ steps.toolchain.outputs.rustc_hash }}
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
